name: Test 
run-name: Run zig tests for commit '${{ github.event.head_commit.message }}' on ${{ github.ref_name }}
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tests 
    steps:
      - uses: actions/checkout@v3
      - name: Setup Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.15.2
      - name: Install glfw
        run: |
          sudo apt install libglfw3 libglfw3-dev
      - name: Run tests
        run: |
          zig build test
        id: md
      - name: Summary results
        if: always()
        run: |
          cat test_output.md >> $GITHUB_STEP_SUMMARY
  tests-rel:
    runs-on: ubuntu-latest
    name: Run tests (release)
    steps:
      - uses: actions/checkout@v3
      - name: Setup Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.15.2
      - name: Install glfw
        run: |
          sudo apt install libglfw3 libglfw3-dev
      - name: Run tests
        run: |
          zig build test -Doptimize=ReleaseFast
        id: md
      - name: Summary results
        if: always()
        run: |
          cat test_output.md >> $GITHUB_STEP_SUMMARY