name: Test 
run-name: Run zig tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build 
    steps:
      - uses: actions/checkout@v3
      - name: Setup Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.14.0
      - name: Install glfw
        run: |
          sudo apt install libglfw3 libglfw3-dev
      - name: Run tests
        run: |
          echo "```" >> $GITHUB_STEP_SUMMARY
          zig build test --summary all 2&>> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
        id: md
      - name: Summary results
        if: always()
        run: |
          cat test_output.md >> $GITHUB_STEP_SUMMARY